# Generated by Django 2.2.7 on 2019-11-12 14:29

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=32)),
                ('api_key', models.CharField(blank=True, max_length=128)),
                ('acc_type', models.CharField(choices=[(0, 'Trial'), (1, 'Full')], default=0, max_length=1)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2019, 11, 19, 16, 29, 47, 702249))),
                ('tasks', models.ManyToManyField(to='django_celery_beat.PeriodicTask')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
