# Generated by Django 2.2.7 on 2020-11-06 12:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 12, 53, 35, 837725)),
        ),
    ]
