# Generated by Django 2.2.7 on 2020-12-06 23:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201106_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 23, 8, 23, 948591)),
        ),
    ]
