# Generated by Django 3.1.4 on 2020-12-07 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201206_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 22, 36, 10, 759025)),
        ),
    ]
