# Generated by Django 3.1.4 on 2020-12-09 21:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201207_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 21, 0, 3, 914521)),
        ),
    ]
