# Generated by Django 3.1.4 on 2020-12-09 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201209_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 22, 42, 52, 826848)),
        ),
    ]
