# Generated by Django 3.1.4 on 2020-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201206_2308'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unit',
            name='main_unit_name_8235be_idx',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='unit',
            name='nickname',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['nickname', 'createdAt'], name='main_unit_nicknam_8674e7_idx'),
        ),
    ]
